### ISSUE TITLE
Docker Spark 

### ISSUE THREAD

**Issue by tbalson** [cloudmesh-book/book-latex-2018#153]
* [ ] Slides: 
* [ ] Handbook:
* [ ] Integrated into handbook:

**Comment by bfeng** [comment]
* [ ] Slides: https://1drv.ms/p/s!AvpSEd2J24STjCOa9Wh9s_t46nV3
* [ ] Handbook: https://github.com/cloudmesh/book/blob/master/section/container/docker-spark.tex
* [ ] Integrated into handbook: Yes. See section "Apache Spark with Docker"
